const test=require('node:test');const assert=require('node:assert/strict');const jwt=require('jsonwebtoken');
process.env.SUPABASE_JWT_SECRET='test-secret-for-authoritative-auth';process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_KEY='test-service-key';
const secret=process.env.SUPABASE_JWT_SECRET;const sign=p=>jwt.sign(p,secret,{expiresIn:'15m'});const biz=(id='biz-a',perms)=>sign({sub:`user-${id}`,user_metadata:{business_id:id,...(perms?{employee_id:`emp-${id}`,staff_role:'custom',permission_set:perms}: {})}});const event=(method,path,token,body)=>({httpMethod:method,headers:token?{authorization:`Bearer ${token}`}:{},queryStringParameters:path||{},body:body?JSON.stringify(body):undefined});async function fn(name){return import(`../${name}.js?test=${Date.now()}-${Math.random()}`)}
for(const name of ['get-lost-found-items','get-lost-found-item','get-lost-found-meta','resolve-lost-found-guest'])test(`${name}: anonymous rejected`,async()=>{const{handler}=await fn(name);assert.equal((await handler(event('GET',{businessId:'biz-a'}))).statusCode,401)});
for(const name of ['create-lost-found-item','update-lost-found-item','collect-lost-found-item','contact-lost-found-guest','upload-lost-found-photo','manage-lost-found-meta'])test(`${name}: anonymous rejected`,async()=>{const{handler}=await fn(name);assert.equal((await handler(event('POST',{},null,{businessId:'biz-a',itemId:'x',item_name:'x',name:'x',action:'add_category',images:['bad']}))).statusCode,401)});
for(const name of ['get-lost-found-items','get-lost-found-item','get-lost-found-meta'])test(`${name}: owner cannot substitute tenant`,async()=>{const{handler}=await fn(name);assert.equal((await handler(event('GET',{businessId:'biz-b',itemId:'item-1'},biz('biz-a')))).statusCode,403)});
test('resolve-lost-found-guest: owner cannot substitute tenant',async()=>{const{handler}=await fn('resolve-lost-found-guest');assert.equal((await handler(event('GET',{businessId:'biz-b',roomId:'room-1'},biz('biz-a')))).statusCode,403)});
for(const name of ['update-lost-found-item','collect-lost-found-item','contact-lost-found-guest','upload-lost-found-photo','manage-lost-found-meta'])test(`${name}: owner cannot substitute tenant`,async()=>{const{handler}=await fn(name);assert.equal((await handler(event('POST',{},biz('biz-a'),{businessId:'biz-b',itemId:'item-1',item_name:'x',collected_by_name:'Guest',method:'email',images:['bad'],action:'add_category',name:'Test'}))).statusCode,403)});
test('create-lost-found-item: owner cannot substitute tenant',async()=>{const{handler}=await fn('create-lost-found-item');assert.equal((await handler(event('POST',{},biz('biz-a'),{businessId:'biz-b',item_name:'wallet'}))).statusCode,403)});
test('create-lost-found-item: employee without create permission rejected',async()=>{const{handler}=await fn('create-lost-found-item');assert.equal((await handler(event('POST',{},biz('biz-a',['canViewLostFound']),{businessId:'biz-a',item_name:'wallet'}))).statusCode,403)});
for(const name of ['collect-lost-found-item','contact-lost-found-guest','upload-lost-found-photo'])test(`${name}: employee without edit permission rejected`,async()=>{const{handler}=await fn(name);assert.equal((await handler(event('POST',{},biz('biz-a',['canViewLostFound']),{businessId:'biz-a',itemId:'item-1',collected_by_name:'Guest',images:['bad']}))).statusCode,403)});
test('update-lost-found-item: employee without edit permission rejected',async()=>{const{handler}=await fn('update-lost-found-item');assert.equal((await handler(event('POST',{},biz('biz-a',['canViewLostFound']),{businessId:'biz-a',itemId:'item-1',item_name:'x'}))).statusCode,403)});
test('manage-lost-found-meta: employee without edit permission rejected',async()=>{const{handler}=await fn('manage-lost-found-meta');assert.equal((await handler(event('POST',{},biz('biz-a',['canViewLostFound']),{businessId:'biz-a',action:'add_category',name:'Test'}))).statusCode,403)});
test('update-lost-found-item: archive requires dispose permission',async()=>{const{handler}=await fn('update-lost-found-item');assert.equal((await handler(event('POST',{},biz('biz-a',['canEditLostFound']),{businessId:'biz-a',itemId:'item-1',status:'archived'}))).statusCode,403)});
test('invalid JWT is rejected rather than fail-open',async()=>{const{handler}=await fn('get-lost-found-item');assert.equal((await handler(event('GET',{businessId:'biz-a',itemId:'item-1'},'not-a-jwt'))).statusCode,401)});

test('update-lost-found-item source enforces explicit workflow transitions',async()=>{const{handler}=await fn('update-lost-found-item');assert.equal(typeof handler,'function');const fs=require('node:fs'),source=fs.readFileSync(path=require('node:path').join(__dirname,'..','update-lost-found-item.js'),'utf8');assert.match(source,/const WORKFLOW_TRANSITIONS =/);assert.match(source,/Invalid Lost & Found status transition/);assert.match(source,/updated_at=eq\.\$\{q\(current\.updated_at\)\}/);assert.match(source,/Booking and room do not match/)});
test('contact-lost-found-guest source constrains methods and terminal states',async()=>{const fs=require('node:fs'),path=require('node:path');const source=fs.readFileSync(path.join(__dirname,'..','contact-lost-found-guest.js'),'utf8');assert.match(source,/const CONTACT_METHODS = new Set/);assert.match(source,/Invalid contact method/);assert.match(source,/const CONTACTABLE_STATUSES = new Set/);assert.match(source,/Guest contact is not allowed for this Lost & Found status/);assert.match(source,/updated_at=eq\.\$\{encodeURIComponent\(item\.updated_at\)\}/)});
test('collect-lost-found-item source constrains collection states and concurrency',async()=>{const fs=require('node:fs'),path=require('node:path');const source=fs.readFileSync(path.join(__dirname,'..','collect-lost-found-item.js'),'utf8');assert.match(source,/const COLLECTABLE_STATUSES = new Set/);assert.match(source,/Lost & Found item is not ready for collection/);assert.match(source,/updated_at=eq\.\$\{encodeURIComponent\(current\.updated_at\)\}/)});
test('upload-lost-found-photo source binds existing uploads to item identity',async()=>{const fs=require('node:fs'),path=require('node:path');const source=fs.readFileSync(path.join(__dirname,'..','upload-lost-found-photo.js'),'utf8');assert.match(source,/const itemId = body\.itemId \|\| body\.item_id \|\| null/);assert.match(source,/id=eq\.\$\{encodeURIComponent\(itemId\)\}&business_id=eq/);assert.match(source,/Upload tag does not match Lost & Found item/)});
