const test=require('node:test');const assert=require('node:assert/strict');const jwt=require('jsonwebtoken');
process.env.SUPABASE_JWT_SECRET='test-secret-for-authoritative-auth';process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_KEY='test-service-key';
const secret=process.env.SUPABASE_JWT_SECRET;const sign=p=>jwt.sign(p,secret,{expiresIn:'15m'});const biz=(id='biz-a',perms)=>sign({sub:`user-${id}`,user_metadata:{business_id:id,...(perms?{employee_id:`emp-${id}`,staff_role:'custom',permission_set:perms}: {})}});const event=(method,path,token,body)=>({httpMethod:method,headers:token?{authorization:`Bearer ${token}`}:{},queryStringParameters:path||{},body:body?JSON.stringify(body):undefined});async function fn(name){return import(`../${name}.js?test=${Date.now()}-${Math.random()}`)}
for(const name of ['get-lost-found-items','get-lost-found-item','get-lost-found-meta','resolve-lost-found-guest'])test(`${name}: anonymous rejected`,async()=>{const{handler}=await fn(name);assert.equal((await handler(event('GET',{businessId:'biz-a'}))).statusCode,401)});
for(const name of ['create-lost-found-item','update-lost-found-item','collect-lost-found-item','contact-lost-found-guest','upload-lost-found-photo','manage-lost-found-meta'])test(`${name}: anonymous rejected`,async()=>{const{handler}=await fn(name);assert.equal((await handler(event('POST',{},null,{businessId:'biz-a',itemId:'x',item_name:'x',name:'x',action:'add_category',images:['bad']}))).statusCode,401)});
test('get-lost-found-items: owner cannot substitute tenant',async()=>{const{handler}=await fn('get-lost-found-items');assert.equal((await handler(event('GET',{businessId:'biz-b'},biz('biz-a')))).statusCode,403)});
test('get-lost-found-item: owner cannot substitute tenant',async()=>{const{handler}=await fn('get-lost-found-item');assert.equal((await handler(event('GET',{businessId:'biz-b',itemId:'item-1'},biz('biz-a')))).statusCode,403)});
test('create-lost-found-item: employee without create permission rejected',async()=>{const{handler}=await fn('create-lost-found-item');assert.equal((await handler(event('POST',{},biz('biz-a',['canViewLostFound']),{businessId:'biz-a',item_name:'wallet'}))).statusCode,403)});
test('update-lost-found-item: employee without edit permission rejected',async()=>{const{handler}=await fn('update-lost-found-item');assert.equal((await handler(event('POST',{},biz('biz-a',['canViewLostFound']),{businessId:'biz-a',itemId:'item-1',item_name:'x'}))).statusCode,403)});
test('manage-lost-found-meta: employee without edit permission rejected',async()=>{const{handler}=await fn('manage-lost-found-meta');assert.equal((await handler(event('POST',{},biz('biz-a',['canViewLostFound']),{businessId:'biz-a',action:'add_category',name:'Test'}))).statusCode,403)});
test('invalid JWT is rejected rather than fail-open',async()=>{const{handler}=await fn('get-lost-found-item');assert.equal((await handler(event('GET',{businessId:'biz-a',itemId:'item-1'},'not-a-jwt'))).statusCode,401)});
