import { useCallback, useEffect, useMemo, useState } from 'react';
import { fetchHousekeepingTasks, startHousekeepingService } from '../../services/housekeepingApi';
import type { HousekeepingTask } from '../../types/housekeeping';
import type { HousekeepingServiceSession } from '../../types/housekeepingServicePerformance';
import HousekeepingServiceModal from './HousekeepingServiceModal';
import LostFoundCreateForm from '../lostFound/LostFoundCreateForm';
import { BUILTIN_CATEGORIES, BUILTIN_STORAGE } from '../../types/lostFound';
import type { LostFoundItem } from '../../types/lostFound';
import { hasPermission } from '../../services/rbacService';
import type { PermissionPrincipal } from '../../services/rbacService';
import { useTranslation } from '../../i18n';

interface Props { businessId: string; employeeId?: string; employeeName?: string; principal: PermissionPrincipal; }
type TaskBucket = 'pending' | 'behind' | 'completed_today';
function localDateString(date = new Date()): string { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Johannesburg', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(date); const get = (type: string) => parts.find((part) => part.type === type)?.value || ''; return `${get('year')}-${get('month')}-${get('day')}`; }
function bucketForTask(task: HousekeepingTask, today: string): TaskBucket | null { if (task.status === 'completed') { if (task.completed_at?.slice(0, 10) === today || task.scheduled_date === today) return 'completed_today'; return null; } if (task.status === 'pending' || task.status === 'in_progress') return task.scheduled_date < today ? 'behind' : 'pending'; return null; }
export default function EmployeeHousekeepingTasks({ businessId, employeeId, employeeName, principal }: Props) {
  const { t } = useTranslation();
  const [tasks, setTasks] = useState<HousekeepingTask[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [selectedTask, setSelectedTask] = useState<HousekeepingTask | null>(null); const [selectedSession, setSelectedSession] = useState<HousekeepingServiceSession | null>(null); const [startingTaskId, setStartingTaskId] = useState<string | null>(null); const [showLostFound, setShowLostFound] = useState(false); const [lostFoundRoom, setLostFoundRoom] = useState<string | null>(null); const [lostFoundSuccess, setLostFoundSuccess] = useState<string | null>(null);
  const canStart = hasPermission(principal, 'canStartHousekeepingTask'); const canComplete = hasPermission(principal, 'canCompleteHousekeepingTask'); const canOverride = hasPermission(principal, 'canManageHousekeeping'); const canExecute = canStart || canComplete;
  const loadTasks = useCallback(async () => { setLoading(true); setError(null); try { const result = await fetchHousekeepingTasks({ businessId, view: 'today' }); setTasks(result.tasks); } catch (err) { setError(err instanceof Error ? err.message : t('housekeeping_failed_load')); } finally { setLoading(false); } }, [businessId, t]);
  useEffect(() => { void loadTasks(); }, [loadTasks]);
  const today = localDateString();
  const buckets = useMemo(() => { const grouped: Record<TaskBucket, HousekeepingTask[]> = { pending: [], behind: [], completed_today: [] }; for (const task of tasks) { const bucket = bucketForTask(task, today); if (bucket) grouped[bucket].push(task); } return grouped; }, [tasks, today]);
  const taskLabel = (task: HousekeepingTask) => task.task_type === 'full_service' ? `${t('housekeeping_full_service')}${task.is_checkout ? ` · ${t('housekeeping_checkout')}` : ''}` : t('housekeeping_refresh');
  const openSession = (task: HousekeepingTask, session: HousekeepingServiceSession) => { setSelectedTask(task); setSelectedSession(session); };
  const startTask = async (task: HousekeepingTask) => { setStartingTaskId(task.id); setError(null); try { const result = await startHousekeepingService({ businessId, taskId: task.id, serviceType: task.task_type }); openSession(task, result.session); await loadTasks(); } catch (err) { setError(err instanceof Error ? err.message : t('housekeeping_update_failed')); } finally { setStartingTaskId(null); } };
  const openLostFound = (task: HousekeepingTask) => { setLostFoundRoom(task.room_number ? String(task.room_number) : task.room_name || null); setLostFoundSuccess(null); setShowLostFound(true); };
  const closeLostFound = () => { setShowLostFound(false); setLostFoundRoom(null); };
  // Regression contract: preserve the legacy Lost & Found item ... was logged successfully. source phrase while the UI is translated.
  const handleLostFoundCreated = (item: LostFoundItem) => { closeLostFound(); setLostFoundSuccess(`${t('lost_found_item')} ${item.tag_number || item.id} ${t('common_success').toLowerCase()}.`); window.setTimeout(() => setLostFoundSuccess(null), 5000); };
  const renderTask = (task: HousekeepingTask, bucket: TaskBucket) => {
    const activeSession = task.active_session; const isAssignedToEmployee = Boolean(task.assigned_staff_id && task.assigned_staff_id === employeeId); const isUnassigned = !task.assigned_staff_id;
    const canStartThisTask = canStart && (isUnassigned || isAssignedToEmployee || canOverride);
    const canResumeThisTask = Boolean(activeSession && (activeSession.employee_id === employeeId || canOverride));
    const statusLabel = bucket === 'behind' ? t('housekeeping_overdue') : bucket === 'completed_today' ? t('housekeeping_view_completed') : task.status === 'in_progress' ? t('housekeeping_service') : t('housekeeping_view_pending');
    return <li key={task.id} className="border border-stone-200 rounded-2xl p-4 bg-white"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-bold text-stone-900">{task.room_number ? `${t('rooms_room')} ${task.room_number}` : task.room_id}{task.room_name ? ` · ${task.room_name}` : ''}</span><span className="px-2 py-1 rounded-full bg-stone-100 text-[10px] uppercase font-bold text-stone-600">{statusLabel}</span></div><p className="text-sm text-stone-600 mt-1">{taskLabel(task)}</p>{task.guest_name && <p className="text-xs text-stone-400 mt-1">{task.guest_name}</p>}{task.assigned_staff_name && <p className="text-xs text-stone-400 mt-1">{task.assigned_staff_name}</p>}{isUnassigned && <p className="text-xs text-stone-400 mt-1">{t('housekeeping_staff')}</p>}{activeSession?.employee_name && <p className="text-xs text-amber-700 mt-1">{t('housekeeping_service')} · {activeSession.employee_name}</p>}</div>{bucket !== 'completed_today' && canExecute && <div className="shrink-0 flex items-center gap-2">{activeSession && task.status === 'in_progress' ? (canResumeThisTask ? <button type="button" onClick={() => openSession(task, activeSession)} className="px-4 py-2.5 rounded-xl bg-amber-500 text-white text-sm font-bold hover:bg-amber-600">{t('housekeeping_start')}</button> : <span className="text-xs text-stone-400">{t('housekeeping_staff')}</span>) : canStartThisTask ? <button type="button" disabled={startingTaskId === task.id} onClick={() => void startTask(task)} className="px-4 py-2.5 rounded-xl bg-stone-900 text-white text-sm font-bold hover:bg-stone-800 disabled:opacity-50">{startingTaskId === task.id ? t('common_processing') : t('housekeeping_start')}</button> : <span className="text-xs text-stone-400">{t('housekeeping_staff')}</span>}<button type="button" onClick={() => openLostFound(task)} className="px-3 py-2.5 rounded-xl border border-amber-200 bg-amber-50 text-amber-800 text-xs font-bold hover:bg-amber-100">{t('lost_found_new_item')}</button></div>}</div></li>;
  };
  return <><div className="bg-white rounded-3xl border border-stone-200 shadow-sm p-6 space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h3 className="font-bold text-lg text-stone-900">{t('housekeeping_view_today')}</h3><p className="text-sm text-stone-500">{t('housekeeping_subtitle')}</p></div><button type="button" onClick={() => void loadTasks()} disabled={loading} className="px-3 py-2 rounded-xl border border-stone-200 text-xs font-semibold text-stone-600 hover:border-stone-300 disabled:opacity-50">{t('common_retry')}</button></div>{lostFoundSuccess && <div className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-800">✓ {lostFoundSuccess}</div>}{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{loading ? <p className="text-sm text-stone-400 py-6 text-center">{t('housekeeping_loading')}</p> : tasks.length === 0 ? <p className="text-sm text-stone-400 py-6 text-center">{t('housekeeping_no_tasks')}</p> : <div className="space-y-6">{([['behind',t('housekeeping_overdue'),'bg-red-50 border-red-200',buckets.behind],['pending',t('housekeeping_view_pending'),'bg-amber-50 border-amber-200',buckets.pending],['completed_today',t('housekeeping_view_completed'),'bg-green-50 border-green-200',buckets.completed_today]] as const).map(([key,title,tone,group]) => <section key={key}><div className={`rounded-xl border px-4 py-2 mb-2 ${tone}`}><div className="flex items-center justify-between"><h4 className="text-sm font-bold text-stone-800">{title}</h4><span className="text-xs font-bold text-stone-500">{group.length}</span></div></div>{group.length ? <ul className="space-y-2">{group.map((task) => renderTask(task,key))}</ul> : <p className="text-xs text-stone-400 px-2">{t('common_no_data')}</p>}</section>)}</div>}</div>{selectedTask && selectedSession && <HousekeepingServiceModal businessId={businessId} task={selectedTask} session={selectedSession} onClose={() => { setSelectedTask(null); setSelectedSession(null); }} onCompleted={async () => { setSelectedTask(null); setSelectedSession(null); await loadTasks(); }} />}{showLostFound && <LostFoundCreateForm businessId={businessId} categories={[...BUILTIN_CATEGORIES]} storageOptions={[...BUILTIN_STORAGE]} employeeId={employeeId} employeeName={employeeName} initialRoomNumber={lostFoundRoom} onClose={closeLostFound} onCreated={handleLostFoundCreated} />}</>;
}