import { useEffect, useState } from 'react';
import { fetchHousekeepingInventory, saveHousekeepingInventory, type HousekeepingInventoryItem } from '../../services/housekeepingInventoryApi';

const DEFAULTS = [
  ['Champagne','minibar'],['Beer A','minibar'],['Beer B','minibar'],['White Wine','minibar'],['Red Wine','minibar'],['Brandy','minibar'],['Whisky','minibar'],['Coke','minibar'],['Sprite','minibar'],['Fanta','minibar'],['Soda','minibar'],['Fruit Juice','minibar'],['Coffee','coffee'],['Tea','coffee'],
] as const;

export default function HousekeepingInventorySettings({ businessId }:{businessId:string}){
 const [items,setItems]=useState<HousekeepingInventoryItem[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [name,setName]=useState(''); const [category,setCategory]=useState<'minibar'|'coffee'|'other'>('minibar'); const [price,setPrice]=useState('');
 useEffect(()=>{let active=true;fetchHousekeepingInventory(businessId).then(rows=>{if(active)setItems(rows);}).catch(e=>{if(active)setError(e.message||'Unable to load inventory catalogue');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;}},[businessId]);
 const add=()=>{const n=name.trim();if(!n)return;setItems(cur=>[...cur,{id:'',business_id:businessId,name:n,category,unit:'each',price:price===''?null:Number(price),currency:'ZAR',active:true,sort_order:cur.length}]);setName('');setPrice('');};
 const save=async()=>{setSaving(true);setError('');try{setItems(await saveHousekeepingInventory(businessId,items));}catch(e){setError(e instanceof Error?e.message:'Unable to save inventory catalogue');}finally{setSaving(false);}};
 const seed=()=>{if(items.length)return;setItems(DEFAULTS.map(([n,c],i)=>({id:'',business_id:businessId,name:n,category:c as any,unit:'each',price:null,currency:'ZAR',active:true,sort_order:i})))};
 if(loading)return <div className="text-sm text-gray-500">Loading inventory catalogue…</div>;
 return <div className="mt-8 pt-6 border-t border-gray-200"><div className="flex items-start justify-between gap-4"><div><h4 className="text-md font-semibold text-gray-900">Minibar & coffee station inventory</h4><p className="text-sm text-gray-500 mt-1">Manage the items housekeepers can record. Prices are stored now for future PMS/NightBridge billing; no guest is charged by FastCheckIn yet.</p></div>{!items.length&&<button type="button" onClick={seed} className="px-3 py-2 rounded-lg border border-gray-300 text-sm font-semibold">Load starter list</button>}</div>{error&&<div className="mt-3 p-3 rounded-lg bg-red-50 text-red-700 text-sm">{error}</div>}<div className="mt-4 grid grid-cols-1 sm:grid-cols-12 gap-2"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add();}} placeholder="Add item (e.g. Local beer)" className="sm:col-span-5 px-3 py-2 border rounded-lg"/><select value={category} onChange={e=>setCategory(e.target.value as any)} className="sm:col-span-3 px-3 py-2 border rounded-lg"><option value="minibar">Minibar</option><option value="coffee">Coffee station</option><option value="other">Other</option></select><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="Price (optional)" className="sm:col-span-2 px-3 py-2 border rounded-lg"/><button type="button" onClick={add} className="sm:col-span-2 px-3 py-2 rounded-lg bg-orange-500 text-white font-semibold">Add</button></div><div className="mt-4 space-y-2">{items.map((item,i)=><div key={item.id||'new-'+i} className="grid grid-cols-1 sm:grid-cols-12 gap-2 items-center border rounded-lg p-2"><input value={item.name} onChange={e=>setItems(cur=>cur.map((x,j)=>j===i?{...x,name:e.target.value}:x))} className="sm:col-span-4 px-2 py-1.5 border rounded"/><select value={item.category} onChange={e=>setItems(cur=>cur.map((x,j)=>j===i?{...x,category:e.target.value as any}:x))} className="sm:col-span-3 px-2 py-1.5 border rounded"><option value="minibar">Minibar</option><option value="coffee">Coffee station</option><option value="other">Other</option></select><input value={item.price==null?'':String(item.price)} onChange={e=>setItems(cur=>cur.map((x,j)=>j===i?{...x,price:e.target.value===''?null:Number(e.target.value)}:x))} inputMode="decimal" placeholder="Price" className="sm:col-span-2 px-2 py-1.5 border rounded"/><button type="button" onClick={()=>setItems(cur=>cur.filter((_,j)=>j!==i))} className="sm:col-span-1 px-2 py-1.5 rounded border border-red-200 text-red-700">Remove</button></div>)}</div><div className="mt-4 flex justify-end"><button type="button" onClick={()=>void save()} disabled={saving} className="px-4 py-2 rounded-lg bg-orange-500 text-white font-semibold disabled:opacity-50">{saving?'Saving…':'Save inventory catalogue'}</button></div></div>;
}
