import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import Logo from '../components/Logo';
import { useTranslation } from '../i18n';

export default function SetPassword() {
  const { token } = useParams<{ token: string }>();
  const navigate = useNavigate();
  const { t } = useTranslation();
  const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(false); const [validToken, setValidToken] = useState(true); const [showPassword, setShowPassword] = useState(false);

  useEffect(() => { const verifyToken = async () => { try { const response = await fetch(`/.netlify/functions/verify-setup-token?token=${token}`); const data = await response.json(); if (!data.valid) { setValidToken(false); setError(t('auth_set_password_invalid_link')); } } catch { setValidToken(false); setError(t('auth_set_password_verify_error')); } }; if (token) verifyToken(); }, [token, t]);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); if (password !== confirmPassword) return setError(t('auth_set_password_mismatch')); if (password.length < 8) return setError(t('auth_set_password_short')); setLoading(true); try { const response = await fetch('/.netlify/functions/set-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, password }) }); const data = await response.json(); if (response.ok) { setSuccess(true); setTimeout(() => navigate('/business/login'), 3000); } else setError(data.error || t('auth_set_password_failed')); } catch { setError(t('auth_set_password_generic_error')); } finally { setLoading(false); } };

  if (!validToken) return <div className="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8"><div className="sm:mx-auto sm:w-full sm:max-w-md"><div className="flex justify-center"><Logo size="lg" /></div></div><div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md"><div className="bg-white py-8 px-4 shadow-xl rounded-lg sm:px-10 text-center"><div className="text-red-600 text-4xl mb-4">⚠️</div><h2 className="text-2xl font-bold text-gray-900 mb-4">{t('auth_set_password_invalid_title')}</h2><p className="text-gray-600 mb-6">{error || t('auth_set_password_invalid_body')}</p><button onClick={() => navigate('/business/login')} className="w-full py-3 px-4 bg-orange-500 text-white rounded-lg hover:bg-orange-600">{t('auth_set_password_return_login')}</button></div></div></div>;
  if (success) return <div className="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8"><div className="sm:mx-auto sm:w-full sm:max-w-md"><div className="flex justify-center"><Logo size="lg" /></div></div><div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md"><div className="bg-white py-8 px-4 shadow-xl rounded-lg sm:px-10 text-center"><div className="text-green-600 text-4xl mb-4">✓</div><h2 className="text-2xl font-bold text-gray-900 mb-4">{t('auth_set_password_success_title')}</h2><p className="text-gray-600 mb-6">{t('auth_set_password_success_body')}</p></div></div></div>;
  return <div className="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8"><div className="sm:mx-auto sm:w-full sm:max-w-md"><div className="flex justify-center"><Logo size="lg" /></div><h2 className="mt-6 text-center text-3xl font-bold text-gray-900">{t('auth_set_password_title')}</h2><p className="mt-2 text-center text-sm text-gray-600">{t('auth_set_password_help')}</p></div><div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md"><div className="bg-white py-8 px-4 shadow-xl rounded-lg sm:px-10"><form className="space-y-6" onSubmit={handleSubmit}>{error && <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm">{error}</div>}<div><label htmlFor="password" className="block text-sm font-medium text-gray-700">{t('auth_set_password_new')}</label><div className="mt-1 relative"><input id="password" name="password" type={showPassword ? 'text' : 'password'} autoComplete="new-password" required value={password} onChange={(e) => setPassword(e.target.value)} className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm placeholder-gray-400 focus:outline-none focus:ring-orange-500 focus:border-orange-500 pr-10" placeholder="••••••••" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? t('auth_set_password_hide') : t('auth_set_password_show')} className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-500 hover:text-gray-700">{showPassword ? '◉' : '◌'}</button></div><p className="text-xs text-gray-500 mt-1">{t('auth_set_password_minimum')}</p></div><div><label htmlFor="confirm-password" className="block text-sm font-medium text-gray-700">{t('auth_set_password_confirm')}</label><input id="confirm-password" name="confirm-password" type={showPassword ? 'text' : 'password'} autoComplete="new-password" required value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm placeholder-gray-400 focus:outline-none focus:ring-orange-500 focus:border-orange-500" placeholder="••••••••" /></div><button type="submit" disabled={loading} className="w-full flex justify-center py-3 px-4 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-orange-500 hover:bg-orange-600 disabled:opacity-50">{loading ? t('auth_set_password_submitting') : t('auth_set_password_continue')}</button></form></div></div></div>;
}
