import React from 'react';
import { Bed, UserCheck, UserX, UserPlus, QrCode } from 'lucide-react';
import { t } from '../../i18n';
import QRCodeModal from '../QRCodeModal';
import RoomAllocationSelect from '../rooms/RoomAllocationSelect';

interface Props { businessId:string; token:string; }
interface Capabilities { guestOverview:boolean; guestPhone:boolean; foodRestrictions:boolean; frontDeskActions:boolean; }

const hasRestrictions=(guest:any)=>{const r=guest?.food_restrictions||{};return Object.entries(r).some(([k,v])=>v===true&&k!=='other_text')||Boolean(r.other_text);};
const restrictionText=(guest:any)=>{const r=guest?.food_restrictions||{};const labels=Object.entries(r).filter(([k,v])=>v===true&&k!=='other_text').map(([k])=>k.replace(/_/g,' '));if(r.other_text)labels.push(String(r.other_text));return labels.join(', ');};
const room=(g:any)=>g.room_number?`Room ${g.room_number}${g.room_name?` · ${g.room_name}`:''}`:'Room not allocated';

function GuestList({items,type,capabilities,onAssigned}:{items:any[];type:'arrival'|'stayover'|'departure';capabilities:Capabilities;onAssigned:(bookingId:string,room:any)=>void}){
  return <div className="space-y-2">{items.length===0?<p className="text-stone-400 text-sm text-center py-4">{type==='arrival'?t('dashboard_no_arrivals'):type==='departure'?t('dashboard_no_checkouts'):t('dashboard_no_stayovers')}</p>:items.map(g=><div key={g.id} className="rounded-xl border border-stone-100 p-3 bg-white"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-semibold text-stone-900 truncate">{g.guest_name}</p><p className="text-xs text-stone-600 mt-1">🌍 {g.guest_country||'Country not provided'}</p><p className="text-xs text-stone-600 mt-1">🏨 {room(g)}</p>{capabilities.guestPhone&&g.guest_phone&&<p className="text-xs text-stone-600 mt-1">☎ {g.guest_phone}</p>}<p className="text-xs text-stone-500 mt-1">{type==='arrival'?`Arrival: ${g.check_in_date}`:type==='departure'?`Departure: ${g.check_out_date}`:`Check-out: ${g.check_out_date}`}</p></div>{capabilities.foodRestrictions&&hasRestrictions(g)&&<span className="shrink-0 rounded-full bg-amber-100 text-amber-800 px-2 py-1 text-[10px] font-bold" title={restrictionText(g)}>⚠️ Food</span>}</div>{capabilities.foodRestrictions&&hasRestrictions(g)&&<div className="mt-2 rounded-lg bg-amber-50 border border-amber-100 px-3 py-2 text-xs text-amber-900"><strong>Food restrictions:</strong> {restrictionText(g)}</div>}{capabilities.frontDeskActions&&<div className="mt-3 pt-3 border-t border-stone-100"><p className="text-[10px] font-bold uppercase tracking-wider text-stone-400 mb-2">Room allocation</p><RoomAllocationSelect businessId={g.business_id||''} bookingId={g.id} checkInDate={g.check_in_date} checkOutDate={g.check_out_date} currentRoomId={g.room_id} currentRoomLabel={g.room_number?room(g):null} onAssigned={(assigned)=>onAssigned(g.id,assigned)}/></div>}</div>)}</div>;
}

export default function EmployeeGuestOverview({businessId,token}:Props){
  const [data,setData]=React.useState<any>({arrivals:[],stayovers:[],departures:[],capabilities:{guestOverview:false,guestPhone:false,foodRestrictions:false,frontDeskActions:false}});
  const [loading,setLoading]=React.useState(true);
  const [error,setError]=React.useState<string|null>(null);
  const [showQRModal,setShowQRModal]=React.useState(false);
  const [businessName,setBusinessName]=React.useState('Property');

  React.useEffect(()=>{let active=true;(async()=>{try{setLoading(true);const r=await fetch(`/.netlify/functions/get-employee-overview?businessId=${encodeURIComponent(businessId)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load guest overview');if(active)setData(d);}catch(e:any){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[businessId,token]);

  React.useEffect(()=>{let active=true;(async()=>{try{const r=await fetch(`/.netlify/functions/get-business-branding?id=${encodeURIComponent(businessId)}`,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}});if(r.ok){const d=await r.json();if(active)setBusinessName(d.trading_name||'Property');}}catch{} })();return()=>{active=false;};},[businessId,token]);

  const handleAssigned=(bookingId:string,assigned:any)=>{setData((prev:any)=>{const update=(items:any[])=>items.map((g:any)=>g.id===bookingId?{...g,room_id:assigned?.id||null,room_number:assigned?.room_number??null,room_name:assigned?.room_name||null}:g);return {...prev,arrivals:update(prev.arrivals||[]),stayovers:update(prev.stayovers||[]),departures:update(prev.departures||[])};});};

  if(loading)return <div className="bg-white rounded-3xl border border-stone-200 p-6 text-sm text-stone-500">Loading guest overview…</div>;
  if(error)return <div className="bg-red-50 border border-red-200 rounded-2xl p-4 text-sm text-red-700">{error}</div>;
  const capabilities:Capabilities=data.capabilities||{guestOverview:true,guestPhone:false,foodRestrictions:false,frontDeskActions:false};
  return <div className="space-y-4">
    <div><p className="text-xs font-bold uppercase tracking-wider text-stone-400">Guest & service overview</p><h2 className="text-xl font-bold text-stone-900 mt-1">Arrivals, stays & departures</h2><p className="text-sm text-stone-500 mt-1">{capabilities.foodRestrictions?'Food restrictions are shown for kitchen and restaurant/service staff.':'Guest information is limited to your operational role.'}</p></div>
    {capabilities.frontDeskActions&&<div className="bg-white rounded-3xl border border-stone-200 shadow-sm p-5"><h3 className="text-sm font-bold text-stone-700 mb-4 flex items-center gap-2"><span className="text-lg">⚡</span> Quick Actions</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><button type="button" onClick={()=>{window.location.href=`/checkin/${businessId}`;}} className="flex items-center gap-3 p-4 border border-stone-200 rounded-2xl hover:bg-orange-50 hover:border-orange-200 transition-all text-left"><div className="p-2 bg-orange-500 rounded-xl text-white"><UserPlus size={18}/></div><div><p className="font-medium text-sm text-stone-900">{t('dashboard_new_checkin')}</p><p className="text-xs text-stone-500">{t('dashboard_new_checkin_desc')}</p></div></button><button type="button" onClick={()=>setShowQRModal(true)} className="flex items-center gap-3 p-4 border border-stone-200 rounded-2xl hover:bg-blue-50 hover:border-blue-200 transition-all text-left"><div className="p-2 bg-blue-500 rounded-xl text-white"><QrCode size={18}/></div><div><p className="font-medium text-sm text-stone-900">{t('dashboard_qr_code')}</p><p className="text-xs text-stone-500">{t('dashboard_qr_code_desc')}</p></div></button></div></div>}
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><section className="bg-white rounded-3xl border border-stone-200 shadow-sm overflow-hidden"><div className="bg-green-50 px-4 py-3 border-b border-green-100 flex items-center gap-2"><UserCheck size={18} className="text-green-600"/><h3 className="font-bold text-sm text-green-800">Arrivals</h3><span className="ml-auto bg-green-100 text-green-800 text-xs font-bold px-2 py-0.5 rounded-full">{data.arrivals.length}</span></div><div className="p-4"><GuestList items={data.arrivals} type="arrival" capabilities={capabilities} onAssigned={handleAssigned}/></div></section><section className="bg-white rounded-3xl border border-stone-200 shadow-sm overflow-hidden"><div className="bg-blue-50 px-4 py-3 border-b border-blue-100 flex items-center gap-2"><Bed size={18} className="text-blue-600"/><h3 className="font-bold text-sm text-blue-800">Current stays</h3><span className="ml-auto bg-blue-100 text-blue-800 text-xs font-bold px-2 py-0.5 rounded-full">{data.stayovers.length}</span></div><div className="p-4"><GuestList items={data.stayovers} type="stayover" capabilities={capabilities} onAssigned={handleAssigned}/></div></section><section className="bg-white rounded-3xl border border-stone-200 shadow-sm overflow-hidden"><div className="bg-amber-50 px-4 py-3 border-b border-amber-100 flex items-center gap-2"><UserX size={18} className="text-amber-600"/><h3 className="font-bold text-sm text-amber-800">Departures</h3><span className="ml-auto bg-amber-100 text-amber-800 text-xs font-bold px-2 py-0.5 rounded-full">{data.departures.length}</span></div><div className="p-4"><GuestList items={data.departures} type="departure" capabilities={capabilities} onAssigned={handleAssigned}/></div></section></div>
    {showQRModal&&<QRCodeModal businessId={businessId} businessName={businessName} onClose={()=>setShowQRModal(false)}/>} 
  </div>;
}
