import React from 'react';
import { Bed, Calendar, ChevronRight, UserCheck, UserX } from 'lucide-react';
import { t } from '../../i18n';

interface Props { businessId:string; token:string; }
const hasRestrictions=(guest:any)=>{const r=guest?.food_restrictions||{};return Object.entries(r).some(([k,v])=>v===true&&k!=='other_text')||Boolean(r.other_text);};
const restrictionText=(guest:any)=>{const r=guest?.food_restrictions||{};const labels=Object.entries(r).filter(([k,v])=>v===true&&k!=='other_text').map(([k])=>k.replace(/_/g,' '));if(r.other_text)labels.push(String(r.other_text));return labels.join(', ');};
const room=(g:any)=>g.room_number?`Room ${g.room_number}${g.room_name?` · ${g.room_name}`:''}`:'Room not allocated';
function GuestList({items,type}:{items:any[];type:'arrival'|'stayover'|'departure'}){return <div className="space-y-2">{items.length===0?<p className="text-stone-400 text-sm text-center py-4">{type==='arrival'?t('dashboard_no_arrivals'):type==='departure'?t('dashboard_no_checkouts'):t('dashboard_no_stayovers')}</p>:items.map(g=><div key={g.id} className="rounded-xl border border-stone-100 p-3 bg-white"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-semibold text-stone-900 truncate">{g.guest_name}</p><p className="text-xs text-stone-600 mt-1">🏨 {room(g)}</p><p className="text-xs text-stone-500 mt-1">{type==='arrival'?`Arrival: ${g.check_in_date}`:type==='departure'?`Departure: ${g.check_out_date}`:`Check-out: ${g.check_out_date}`}</p></div>{hasRestrictions(g)&&<span className="shrink-0 rounded-full bg-amber-100 text-amber-800 px-2 py-1 text-[10px] font-bold" title={restrictionText(g)}>⚠️ Food</span>}</div>{hasRestrictions(g)&&<div className="mt-2 rounded-lg bg-amber-50 border border-amber-100 px-3 py-2 text-xs text-amber-900"><strong>Food restrictions:</strong> {restrictionText(g)}</div>}</div>)}</div>}
export default function EmployeeGuestOverview({businessId,token}:Props){const [data,setData]=React.useState<any>({arrivals:[],stayovers:[],departures:[]}),[loading,setLoading]=React.useState(true),[error,setError]=React.useState<string|null>(null);React.useEffect(()=>{let active=true;(async()=>{try{setLoading(true);const r=await fetch(`/.netlify/functions/get-employee-overview?businessId=${encodeURIComponent(businessId)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load guest overview');if(active)setData(d);}catch(e:any){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[businessId,token]);if(loading)return <div className="bg-white rounded-3xl border border-stone-200 p-6 text-sm text-stone-500">Loading guest overview…</div>;if(error)return <div className="bg-red-50 border border-red-200 rounded-2xl p-4 text-sm text-red-700">{error}</div>;return <div className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-wider text-stone-400">Guest & service overview</p><h2 className="text-xl font-bold text-stone-900 mt-1">Arrivals, stays & departures</h2><p className="text-sm text-stone-500 mt-1">Food restrictions are highlighted for kitchen and restaurant/service staff.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><section className="bg-white rounded-3xl border border-stone-200 shadow-sm overflow-hidden"><div className="bg-green-50 px-4 py-3 border-b border-green-100 flex items-center gap-2"><UserCheck size={18} className="text-green-600"/><h3 className="font-bold text-sm text-green-800">Arrivées du jour</h3><span className="ml-auto bg-green-100 text-green-800 text-xs font-bold px-2 py-0.5 rounded-full">{data.arrivals.length}</span></div><div className="p-4"><GuestList items={data.arrivals} type="arrival"/></div></section><section className="bg-white rounded-3xl border border-stone-200 shadow-sm overflow-hidden"><div className="bg-blue-50 px-4 py-3 border-b border-blue-100 flex items-center gap-2"><Bed size={18} className="text-blue-600"/><h3 className="font-bold text-sm text-blue-800">Séjours en cours</h3><span className="ml-auto bg-blue-100 text-blue-800 text-xs font-bold px-2 py-0.5 rounded-full">{data.stayovers.length}</span></div><div className="p-4"><GuestList items={data.stayovers} type="stayover"/></div></section><section className="bg-white rounded-3xl border border-stone-200 shadow-sm overflow-hidden"><div className="bg-amber-50 px-4 py-3 border-b border-amber-100 flex items-center gap-2"><UserX size={18} className="text-amber-600"/><h3 className="font-bold text-sm text-amber-800">Départs du jour</h3><span className="ml-auto bg-amber-100 text-amber-800 text-xs font-bold px-2 py-0.5 rounded-full">{data.departures.length}</span></div><div className="p-4"><GuestList items={data.departures} type="departure"/></div></section></div></div>;}
