import { useEffect, useMemo, useState } from 'react';
import { getAuthHeader } from '../utils/auth';

type Status = 'new' | 'open_not_contacted' | 'in_progress' | 'attempted_to_contact' | 'connected_bad_timing' | 'qualified' | 'unqualified' | 'converted';
interface Enquiry { id:string; topic:string; status:Status; full_name:string; company_name:string; email:string; telephone:string; address?:string; website?:string; total_rooms?:number; total_establishments?:number; comments?:string; created_at:string; updated_at:string; assigned_employee_id?:string|null; assigned_employee_name?:string|null; archived_at?:string|null; }
interface Employee { id:string; full_name:string; email:string; role?:string|null; active:boolean; }
interface Activity { id:string; employee_name?:string|null; activity_type:string; comment:string; created_at:string; }
const STATUS_LABELS:Record<Status,string>={new:'New',open_not_contacted:'Open / Not Contacted',in_progress:'In Progress / Working',attempted_to_contact:'Attempted to Contact',connected_bad_timing:'Connected / Bad Timing',qualified:'Qualified',unqualified:'Unqualified / Disqualified',converted:'Converted'};
const statusClass=(s:Status)=>({new:'bg-blue-100 text-blue-800',open_not_contacted:'bg-gray-100 text-gray-800',in_progress:'bg-amber-100 text-amber-800',attempted_to_contact:'bg-purple-100 text-purple-800',connected_bad_timing:'bg-orange-100 text-orange-800',qualified:'bg-green-100 text-green-800',unqualified:'bg-red-100 text-red-800',converted:'bg-emerald-100 text-emerald-800'}[s]);

export default function SuperAdminMiniCRM(){
 const [items,setItems]=useState<Enquiry[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[selected,setSelected]=useState<Enquiry|null>(null),[activities,setActivities]=useState<Activity[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[comment,setComment]=useState('');
 const [status,setStatus]=useState(''),[employee,setEmployee]=useState(''),[topic,setTopic]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const load=async()=>{setLoading(true);try{const q=new URLSearchParams();if(status)q.set('status',status);if(employee)q.set('employeeId',employee);if(topic)q.set('topic',topic);if(from)q.set('from',from+'T00:00:00Z');if(to)q.set('to',to+'T23:59:59Z');const r=await fetch('/.netlify/functions/superadmin-mini-crm?'+q,{headers:getAuthHeader()});const d=await r.json();if(r.ok){setItems(d.data||[]);setEmployees(d.employees||[]);}}finally{setLoading(false);}};
 useEffect(()=>{load();},[status,employee,topic,from,to]);
 const topics=useMemo(()=>Array.from(new Set(items.map(i=>i.topic))).sort(),[items]);
 const open=async(item:Enquiry)=>{setSelected(item);setComment('');const r=await fetch('/.netlify/functions/superadmin-mini-crm?enquiryId='+encodeURIComponent(item.id),{headers:getAuthHeader()});const d=await r.json();setActivities(d.activities||[]);};
 const patch=async(body:any)=>{if(!selected)return;setSaving(true);try{const r=await fetch('/.netlify/functions/superadmin-mini-crm',{method:'PATCH',headers:{'Content-Type':'application/json',...getAuthHeader()},body:JSON.stringify({id:selected.id,...body})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Update failed');setSelected(d.data);setItems(v=>v.map(i=>i.id===selected.id?d.data:i));}catch(e){alert((e as Error).message);}finally{setSaving(false);}};
 const addComment=async()=>{if(!selected||!comment.trim())return;setSaving(true);try{const r=await fetch('/.netlify/functions/superadmin-mini-crm',{method:'POST',headers:{'Content-Type':'application/json',...getAuthHeader()},body:JSON.stringify({id:selected.id,comment,activityType:'comment',employeeId:selected.assigned_employee_id||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save comment');setActivities(v=>[d.data,...v]);setComment('');}catch(e){alert((e as Error).message);}finally{setSaving(false);}};
 const remove=async()=>{if(!selected||!confirm('Permanently delete this inquiry and its conversation history?'))return;setSaving(true);try{const r=await fetch('/.netlify/functions/superadmin-mini-crm',{method:'DELETE',headers:getAuthHeader(),body:JSON.stringify({id:selected.id})});if(!r.ok)throw new Error('Delete failed');setItems(v=>v.filter(i=>i.id!==selected.id));setSelected(null);}catch(e){alert((e as Error).message);}finally{setSaving(false);}};
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6"><div className="bg-white rounded-lg shadow overflow-hidden">
  <div className="px-6 py-4 bg-amber-50 border-b border-amber-200"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold text-amber-800">Mini-CRM — Website Enquiries ({items.length})</h2><div className="flex flex-wrap gap-2"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded border px-2 py-1 text-sm"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded border px-2 py-1 text-sm"/><select value={topic} onChange={e=>setTopic(e.target.value)} className="rounded border px-2 py-1 text-sm"><option value="">All types</option>{topics.map(t=><option key={t}>{t}</option>)}</select><select value={employee} onChange={e=>setEmployee(e.target.value)} className="rounded border px-2 py-1 text-sm"><option value="">All employees</option><option value="unassigned">Unassigned</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded border px-2 py-1 text-sm"><option value="">All statuses</option>{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div></div>
  <div className="divide-y divide-gray-200">{loading?<div className="p-8 text-center text-gray-500">Loading enquiries…</div>:items.length===0?<div className="p-8 text-center text-gray-500">No enquiries match the filters.</div>:items.map(item=><button type="button" key={item.id} onClick={()=>open(item)} className="w-full text-left px-6 py-4 hover:bg-gray-50"><div className="grid grid-cols-1 md:grid-cols-[120px_1.2fr_1fr_1fr_190px] gap-3 items-center"><div className="text-sm text-gray-500">{new Date(item.created_at).toLocaleDateString()}</div><div><div className="font-semibold text-gray-900">{item.full_name}</div><div className="text-xs text-gray-500">{item.company_name}</div></div><div className="text-sm text-gray-700">{item.topic}</div><div className="text-sm text-gray-600">{item.assigned_employee_name||'Unassigned'}</div><span className={'justify-self-start rounded-full px-2.5 py-1 text-xs font-semibold '+statusClass(item.status)}>{STATUS_LABELS[item.status]}</span></div></button>)}</div>
 </div>{selected&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="bg-white rounded-xl shadow-xl w-full max-w-4xl max-h-[92vh] overflow-y-auto"><div className="sticky top-0 bg-white border-b px-6 py-4 flex justify-between items-center"><div><h3 className="text-xl font-semibold text-gray-900">{selected.full_name}</h3><p className="text-sm text-gray-500">{selected.company_name} · {selected.topic}</p></div><button onClick={()=>setSelected(null)} className="text-gray-500 text-xl">✕</button></div><div className="p-6 space-y-6">
  <div className="grid md:grid-cols-2 gap-3 text-sm"><div><b>Email:</b> <a className="text-blue-600" href={'mailto:'+selected.email}>{selected.email}</a></div><div><b>Telephone:</b> {selected.telephone}</div>{selected.website&&<div><b>Website:</b> {selected.website}</div>}{selected.address&&<div><b>Address:</b> {selected.address}</div>}<div><b>Captured:</b> {new Date(selected.created_at).toLocaleString()}</div></div>
  {selected.comments&&<div className="rounded-lg bg-gray-50 p-4 text-sm"><b>Original enquiry</b><div className="mt-2 whitespace-pre-wrap">{selected.comments}</div></div>}
  <div className="grid md:grid-cols-2 gap-4"><div><label className="block text-xs font-semibold text-gray-500 mb-1">Status</label><select disabled={saving} value={selected.status} onChange={e=>{setStatus(e.target.value);patch({status:e.target.value})}} className="w-full rounded-lg border px-3 py-2">{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div><label className="block text-xs font-semibold text-gray-500 mb-1">Assigned employee</label><div className="flex gap-2"><select disabled={saving} value={selected.assigned_employee_id||''} onChange={e=>patch({assignedEmployeeId:e.target.value})} className="flex-1 rounded-lg border px-3 py-2"><option value="">Unassigned</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select><button disabled={saving||!selected.assigned_employee_id} onClick={()=>patch({assignedEmployeeId:selected.assigned_employee_id,takeover:true})} className="rounded-lg bg-stone-900 px-3 py-2 text-white text-sm">Take over</button></div></div></div>
  <div><h4 className="font-semibold text-gray-900 mb-3">Conversation history</h4><div className="space-y-3">{activities.length===0?<p className="text-sm text-gray-500">No conversation notes yet.</p>:activities.map(a=><div key={a.id} className="border rounded-lg p-3"><div className="flex justify-between text-xs text-gray-500"><span>{a.employee_name||'Super Admin'} · {a.activity_type}</span><span>{new Date(a.created_at).toLocaleString()}</span></div><p className="mt-2 text-sm whitespace-pre-wrap">{a.comment}</p></div>)}</div><div className="mt-4"><textarea value={comment} onChange={e=>setComment(e.target.value)} rows={3} placeholder="Record what was discussed…" className="w-full rounded-lg border px-3 py-2"/><div className="mt-2 flex justify-between"><button disabled={saving||!comment.trim()} onClick={addComment} className="rounded-lg bg-amber-500 px-4 py-2 text-white">Add comment</button><div className="flex gap-2"><button disabled={saving} onClick={()=>patch({archived:true})} className="rounded-lg bg-gray-200 px-4 py-2 text-gray-700">Archive</button><button disabled={saving} onClick={remove} className="rounded-lg bg-red-600 px-4 py-2 text-white">Delete</button></div></div></div></div>
 </div></div></div>}
 </div>;
}
